trigger: none

parameters:
  - name: serviceName
    displayName: Service Name
    type: string
    default: service supplier
  - name: managerName
    displayName: Manager Name
    type: string
    default: carl
    values: 
    - carl
    - darren
  - name: numberOfInstances
    displayName: Number Of Instances
    type: number
    default: 2
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
  - name: runTests
    displayName: Run Tests
    type: boolean
    default: true
  - name: creditRating
    displayName: Credit Rating
    type: string
    default: poor
    values:
      - poor
      - ok
      - good
      - great

extends:
  template: /azure/templates/start.yml

  parameters:
    myStringName: ${{ parameters.serviceName }}
    myNumber: ${{ parameters.numberOfInstances }}
    myMultiString: ${{ parameters.managerName }}
    myBoolean: ${{ parameters.runTests }}
    creditRating: ${{ parameters.creditRating }}
