
name: BC-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: 
   - main

pool: 
  vmImage: ubuntu-latest

variables: 
  - name: variable
    value: monday

stages:
 - stage: stage1
   displayName: stage1
   variables: 
    - name: variable
      value: tuesday
   jobs:
   - job: job1
     variables:
       - name: variable
         value: wednesday
     steps: 
     - checkout: self
     - script: | 
         echo "Hello World!"
         echo "##vso[task.setvariable variable=variable;isOutput=false]thursday"
       displayName: Hello World
     - script: 'echo "Variable: $(variable)"'
       displayName: Variables


      