
name: BC-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: 
   - main

pool: 
  vmImage: ubuntu-latest

variables: 
  - name: variable
    value: monday

stages:
 - stage: stage1
   displayName: stage1
   variables: 
    - name: variable
      value: tuesday
   jobs:
   - job: job1
     variables:
       - name: variable
         value: wednesday
     steps: 
     - checkout: self
     - script: | 
         echo "Hello World!"
         echo "##vso[task.setvariable variable=variable;isOutput=true]thursday"
       name: day
       displayName: Hello World
     - script: 'echo "Variable: $(day.variable)"'
       displayName: Variables

 - stage: stage2
   displayName: stage2
   dependsOn: stage1
   jobs:
    - job: stage2_job_A
      condition: eq(stageDependencies.stage1.job1.outputs[ValidateVar.VarKey], TEST)
      variables:
       - varFromStageA: echo "##vso[task.setvariable variable=variable;isOutput=true]thursday"
      steps:
      - checkout: self
      - script: |
         - 'echo "Variable: $(day.variable)"'
       


      