
name: BC-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: 
   - main

pool: 
  vmImage: ubuntu-latest

variables: 
  - name: variable
    value: monday
  - group: Latte

stages:
 - stage: stage1
   displayName: stage1
   variables: 
    - name: stageVariable
      value: tuesday
   jobs:
   - job: job1
     variables:
       - name: jobVariable
         value: wednesday
     steps: 
     - checkout: none
     - task: CmdLine@2
       displayName: 'DEBUG: show environment variables'
       inputs:
        script: 'printenv'
     - script: | 
         echo "Hello World!"
         echo "##vso[task.setvariable variable=taskOutput;isOutput=true]thursday"
       name: day
       displayName: Hello World
     - script: 'echo "stageVariable, $(stageVariable), jobVariable: $(jobVariable), taskVariable, $(day.taskOutput), Build_BuildId: $(Build.BuildId) Size: $(size) Extra: $(extra) oldWay: $(oldWay)"'
       displayName: Variables
   - job: job2
     variables:
        variableFromJob1: $[ dependencies.job1.outputs['day.taskOutput']]
     steps:
      - checkout: none
      - script: |
          echo "stageVariable, $(stageVariable), jobVariable, $(jobVariable), stage1 Variable: $(varFromStage1) taskVariable: $(day.taskOutput)" 
     

 - stage: stage2
   displayName: stage2
   #dependsOn: stage1
   jobs:
    - job: stage2_job_A
      variables:
        varFromStage1: $[ stageDependencies.stage1.job1.outputs['day.taskOutput']]
      steps:
      - checkout: none
      - script: | 
          echo "Hello World!"
          echo "##vso[task.setvariable variable=taskOutput;isOutput=true]friday"
        name: day
        displayName: Hello World
      - script: |
          echo "stageVariable, $(stageVariable), jobVariable, $(jobVariable), stage1 Variable: $(varFromStage1) taskVariable: $(day.taskOutput)"
       


      