
name: BC-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: 
   - main

pool: 
  vmImage: ubuntu-latest

variables: 
  - name: variable
    value: monday

stages:
 - stage: stage1
   displayName: stage1
   variables: 
    - name: variable
      value: tuesday
   jobs:
   - job: job1
     variables:
       - name: variable
         value: wednesday
     steps: 
     - checkout: self
     - script: | 
         echo "Hello World!"
         echo "##vso[task.setvariable variable=variable;isOutput=true]thursday"
       name: day
       displayName: Hello World
     - script: 'echo "Variable: $(day.variable)"'
       displayName: Variables

     - script: |
        echo "Variable:"
        echo $(ValidateVar.variable)
       name: Print_Key_value

 - stage: stage2
   displayName: stage2
   dependsOn: stage1
   jobs:
    - job: stage2_job_A
      variables:
       - varFromStage1: $[##vso[task.setvariable variable=variable;isOutput=true]]
      steps:
      - checkout: none
      - script: |
         - 'echo "Variable: $(day.variable)"'
       


      