
name: BC-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: 
   - main

pool: 
  vmImage: ubuntu-latest

variables: 
  - name: variable
    value: monday

stages:
 - stage: stage1
   displayName: stage1
   jobs:
   - job: job1
     steps: 
     - checkout: self
     - script: 'echo "Hello World!"'
       displayName: Hello World
     - script: 'echo "Variable: $(variable)"'


      