parameters:
- name: myStringName
  type: string
  default: string Value
- name: myMultiString
  type: string
  default: default
- name: myNumber
  type: number
  default: 2
- name: myBoolean
  type: boolean
  default: true
- name: creditRating
  type: string
  default: ok

variables:
 - name: testCondition
   value: false

resources:
  repositories:
  - repository: lsm-servicefabric
    type: github
    endpoint: 'github.com_sfab-bankingcloud'
    name: Sage/lsm-servicefabric
    ref: refs/heads/production

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        steps:
          - script: echo runnning build
      - job: unitTest
        dependsOn: build
        steps:
          - script: echo running test
  - stage: deploy
    displayName: Deploy
    dependsOn: build
    jobs:
     - job: deploy
       steps:
        - script: echo running deploy 
  - ${{ if eq(parameters.myBoolean, true) }}: 
    - stage: test
      displayName: Test
      dependsOn: deploy
      jobs:
        - job: test
          steps:
            - script: echo running test
        ###############################################
        # Security Testing
        ###############################################
        - job: securityTests
          timeoutInMinutes: 90
          continueOnError: true
          displayName: 'Security Testing'
          dependsOn:
          - test
          pool:
            vmImage: 'ubuntu-20.04'
          container:
            image: sagelsmdevops.azurecr.io/sage/lsm/fortify:latest
            endpoint: 'LSMDocker'  
          steps:
          - checkout: self
          - checkout: lsm-servicefabric
          - template: security/securitytests.yaml@lsm-servicefabric
            parameters:
              ThreadfixAppId: '1'
              ThreadfixUri: https://www.google.co.uk
              ThreadfixAppKey: secret
              JSCode: false
              ExcludeFolders: '**/*.tests/**/*,**/*.Tests/**,**/*Test*/**,**/test/**,**/*absa/**,**/*narrativedictionary/**'
              DependencyScanFolder: $(Build.SourcesDirectory)
              DependencySuppressionFile: $(Build.SourcesDirectory)
              FortifyScanFolder: $(Build.SourcesDirectory)
              CheckoutPath: '/lsm-servicefabric'
  - stage: notification
    displayName: Notification
    ${{ if eq(parameters.myBoolean, true) }}:
      dependsOn: test
    ${{ if ne(parameters.myBoolean, true) }}:
      dependsOn: deploy
    jobs:
      - job: notify
        steps: 
        - ${{ each parameter in parameters }}:
          - script: echo ${{ parameter.Value }}
            displayName: Parameter Name ${{ parameter.Key }}
    